# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 379)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/agenda.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_SearchItem = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_SearchItem.sizePolicy().hasHeightForWidth())
        self.lineEdit_SearchItem.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_SearchItem.setFont(font)
        self.lineEdit_SearchItem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_SearchItem.setObjectName("lineEdit_SearchItem")
        self.horizontalLayout.addWidget(self.lineEdit_SearchItem)
        self.pushButton_Find = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Find.sizePolicy().hasHeightForWidth())
        self.pushButton_Find.setSizePolicy(sizePolicy)
        self.pushButton_Find.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Find.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/find.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Find.setIcon(icon1)
        self.pushButton_Find.setObjectName("pushButton_Find")
        self.horizontalLayout.addWidget(self.pushButton_Find)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.minhaLista_listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minhaLista_listWidget.sizePolicy().hasHeightForWidth())
        self.minhaLista_listWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.minhaLista_listWidget.setFont(font)
        self.minhaLista_listWidget.setObjectName("minhaLista_listWidget")
        self.gridLayout.addWidget(self.minhaLista_listWidget, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_AddingItem = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_AddingItem.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_AddingItem.setObjectName("lineEdit_AddingItem")
        self.horizontalLayout_2.addWidget(self.lineEdit_AddingItem)
        self.pushButton_Create = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Create.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Create.sizePolicy().hasHeightForWidth())
        self.pushButton_Create.setSizePolicy(sizePolicy)
        self.pushButton_Create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_Create.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_Create.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/add.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Create.setIcon(icon2)
        self.pushButton_Create.setIconSize(QtCore.QSize(18, 18))
        self.pushButton_Create.setObjectName("pushButton_Create")
        self.horizontalLayout_2.addWidget(self.pushButton_Create)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lista Todo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
